language: java
script: "./gradlew clean build"
deploy:
  provider: releases
  api_key:
    secure: E1VHLvqW2ZUwj4g/PHe6MVEuf/wmVLhNXktPwWOWOUnhoehqg9ElK7c1vgRt4I9KXawTikfPsVkqzr8Atj3PSDAkpWBhIpttT1OuBhRVbBigmEdKpUESQS5yCCoAClz8+FP+Oh6athyFAYTMAb7B9CU91V6x/XJo7/00/HXp3xTs5pDB6u1F78ZyJxYB3kyt5mBw23u1Hdw61ouMGQMiApz8BGS9jW2If/wFHiBThiqF4MpxMOhknadkMav6I/Ea1mcCXmv/PvzM2wyHSrTJKV8Y/nxOXkiiRVbooKpzKBmhbOXAlb/G51CigyXz2tTVO6YndG7PDtH7RVsKXq/+fnXB/v5LN2VYTV7sFBwOHEoK3BV04a+gwWhezpICDi35lFuCPajmaJzJDoPKOwgpOLjMfsXdF7nwO/DOZzqXnZZ8f0tXOdkYFKzJDAViKWuqhCUqWAOx6r1JRyyqh23hz4BTJmcx44LJpU4mCNQjKunv2CNc2UGROxYJVQ6C6LKXpqkMMJ5v1SRmpP+5S52/Tz9LFpoXmQQnyV55nd58SNREjmnaEEM+7J6jUH+ED5Qm5t4YQ/P57NiIiVmfld3DOjzHyZKYaAKWLGYgt0S8LwgXGi5/94+ry8RA3bm3ljN0JNjAId+xFOFqWUNPIjHQAgTPtrs0R0Rjz7cg/YJvN9k=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-ansible-tower-plugin
